package com.kingdomlife.app;

public class DailyVerseData {

    public static String[] getVerses() {
        return new String[] {

          "Genesis 1:1 — In the beginning God created the heaven and the earth.",
"Genesis 15:1 — Fear not, Abram: I am thy shield, and thy exceeding great reward.",
"Exodus 14:14 — The LORD shall fight for you, and ye shall hold your peace.",
"Deuteronomy 31:8 — And the LORD, he it is that doth go before thee; he will be with thee, he will not fail thee, neither forsake thee: fear not, neither be dismayed.",
"Joshua 1:9 — Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.",
"Judges 6:12 — The LORD is with thee, thou mighty man of valour.",
"Ruth 2:12 — The LORD recompense thy work, and a full reward be given thee of the LORD God of Israel, under whose wings thou art come to trust.",
"1 Samuel 16:7 — For man looketh on the outward appearance, but the LORD looketh on the heart.",
"2 Samuel 22:31 — As for God, his way is perfect; the word of the LORD is tried: he is a buckler to all them that trust in him.",
"1 Kings 8:61 — Let your heart therefore be perfect with the LORD our God, to walk in his statutes, and to keep his commandments, as at this day.",
"2 Kings 20:5 — I have heard thy prayer, I have seen thy tears: behold, I will heal thee.",
"1 Chronicles 16:11 — Seek the LORD and his strength, seek his face continually.",
"2 Chronicles 7:14 — If my people, which are called by my name, shall humble themselves, and pray, and seek my face, and turn from their wicked ways; then will I hear from heaven, and will forgive their sin, and will heal their land.",
"Ezra 7:10 — For Ezra had prepared his heart to seek the law of the LORD, and to do it, and to teach in Israel statutes and judgments.",
"Nehemiah 8:10 — The joy of the LORD is your strength.",
"Esther 4:14 — And who knoweth whether thou art come to the kingdom for such a time as this?",
"Job 19:25 — For I know that my redeemer liveth, and that he shall stand at the latter day upon the earth.",
"Psalm 23:1 — The LORD is my shepherd; I shall not want.",
"Psalm 27:1 — The LORD is my light and my salvation; whom shall I fear?",
"Psalm 34:8 — O taste and see that the LORD is good: blessed is the man that trusteth in him.",
"Psalm 37:4 — Delight thyself also in the LORD; and he shall give thee the desires of thine heart.",
"Psalm 46:10 — Be still, and know that I am God.",
"Psalm 55:22 — Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved.",
"Psalm 56:3 — What time I am afraid, I will trust in thee.",
"Psalm 91:1 — He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.",
"Psalm 100:5 — For the LORD is good; his mercy is everlasting; and his truth endureth to all generations.",
"Psalm 119:105 — Thy word is a lamp unto my feet, and a light unto my path.",
"Proverbs 3:5 — Trust in the LORD with all thine heart; and lean not unto thine own understanding.",
"Proverbs 16:3 — Commit thy works unto the LORD, and thy thoughts shall be established.",
"Ecclesiastes 3:1 — To every thing there is a season, and a time to every purpose under the heaven.",
          "Song of Solomon 2:4 — He brought me to the banqueting house, and his banner over me was love.",
"Isaiah 26:3 — Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.",
"Isaiah 40:31 — But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles.",
"Isaiah 41:10 — Fear thou not; for I am with thee: be not dismayed; for I am thy God.",
"Isaiah 43:2 — When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee.",
"Isaiah 53:5 — But he was wounded for our transgressions, he was bruised for our iniquities.",
"Isaiah 55:8 — For my thoughts are not your thoughts, neither are your ways my ways, saith the LORD.",
"Jeremiah 17:7 — Blessed is the man that trusteth in the LORD, and whose hope the LORD is.",
"Jeremiah 29:11 — For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil.",
"Lamentations 3:23 — They are new every morning: great is thy faithfulness.",
"Ezekiel 36:26 — A new heart also will I give you, and a new spirit will I put within you.",
"Daniel 6:27 — He delivereth and rescueth, and he worketh signs and wonders in heaven and in earth.",
"Hosea 6:3 — Then shall we know, if we follow on to know the LORD.",
"Joel 2:13 — And rend your heart, and not your garments, and turn unto the LORD your God.",
"Amos 5:14 — Seek good, and not evil, that ye may live.",
"Micah 6:8 — He hath shewed thee, O man, what is good; and what doth the LORD require of thee.",
"Nahum 1:7 — The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.",
"Habakkuk 2:4 — But the just shall live by his faith.",
"Zephaniah 3:17 — The LORD thy God in the midst of thee is mighty; he will save.",
"Haggai 2:9 — The glory of this latter house shall be greater than of the former.",
"Zechariah 4:6 — Not by might, nor by power, but by my spirit, saith the LORD of hosts.",
"Malachi 3:10 — Prove me now herewith, saith the LORD of hosts, if I will not open you the windows of heaven.",
"Matthew 5:14 — Ye are the light of the world. A city that is set on an hill cannot be hid.",
"Matthew 6:33 — But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.",
"Matthew 11:28 — Come unto me, all ye that labour and are heavy laden, and I will give you rest.",
"Matthew 22:37 — Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind.",
"Mark 10:27 — With men it is impossible, but not with God: for with God all things are possible.",
"Luke 1:37 — For with God nothing shall be impossible.",
"Luke 6:31 — And as ye would that men should do to you, do ye also to them likewise.",
"John 3:16 — For God so loved the world, that he gave his only begotten Son.",
    "John 8:12 — I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.",
"John 14:6 — I am the way, the truth, and the life: no man cometh unto the Father, but by me.",
"John 14:27 — Peace I leave with you, my peace I give unto you.",
"John 15:5 — I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit.",
"Acts 1:8 — But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me.",
"Acts 16:31 — Believe on the Lord Jesus Christ, and thou shalt be saved.",
"Romans 5:8 — But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.",
"Romans 8:28 — And we know that all things work together for good to them that love God.",
"Romans 8:38 — For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, shall be able to separate us from the love of God.",
"Romans 12:2 — And be not conformed to this world: but be ye transformed by the renewing of your mind.",
"1 Corinthians 10:13 — God is faithful, who will not suffer you to be tempted above that ye are able.",
"1 Corinthians 13:13 — And now abideth faith, hope, charity, these three; but the greatest of these is charity.",
"1 Corinthians 15:58 — Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord.",
"2 Corinthians 5:17 — Therefore if any man be in Christ, he is a new creature: old things are passed away.",
"2 Corinthians 12:9 — My grace is sufficient for thee: for my strength is made perfect in weakness.",
"Galatians 5:22 — But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith.",
"Ephesians 2:8 — For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.",
"Ephesians 6:11 — Put on the whole armour of God, that ye may be able to stand against the wiles of the devil.",
"Philippians 4:4 — Rejoice in the Lord alway: and again I say, Rejoice.",
"Philippians 4:6 — Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.",
"Philippians 4:13 — I can do all things through Christ which strengtheneth me.",
"Colossians 3:2 — Set your affection on things above, not on things on the earth.",
"1 Thessalonians 5:16 — Rejoice evermore.",
"1 Thessalonians 5:17 — Pray without ceasing.",
"1 Thessalonians 5:18 — In every thing give thanks: for this is the will of God in Christ Jesus concerning you.",
"2 Timothy 1:7 — For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.",
"2 Timothy 3:16 — All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction.",
"Hebrews 11:1 — Now faith is the substance of things hoped for, the evidence of things not seen.",
"James 1:5 — If any of you lack wisdom, let him ask of God, that giveth to all men liberally.",
"1 Peter 5:7 — Casting all your care upon him; for he careth for you.",
    "1 Peter 5:8 — Be sober, be vigilant; because your adversary the devil, as a roaring lion, walketh about.",
"2 Peter 3:18 — But grow in grace, and in the knowledge of our Lord and Saviour Jesus Christ.",
"1 John 1:9 — If we confess our sins, he is faithful and just to forgive us our sins.",
"1 John 4:4 — Greater is he that is in you, than he that is in the world.",
"1 John 4:7 — Beloved, let us love one another: for love is of God.",
"1 John 4:19 — We love him, because he first loved us.",
"2 John 1:6 — And this is love, that we walk after his commandments.",
"3 John 1:4 — I have no greater joy than to hear that my children walk in truth.",
"Jude 1:20 — But ye, beloved, building up yourselves on your most holy faith, praying in the Holy Ghost.",
"Revelation 1:8 — I am Alpha and Omega, the beginning and the ending, saith the Lord.",
"Revelation 3:20 — Behold, I stand at the door, and knock.",
"Revelation 21:4 — And God shall wipe away all tears from their eyes; and there shall be no more death.",
"Psalm 19:14 — Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight.",
"Psalm 25:4 — Shew me thy ways, O LORD; teach me thy paths.",
"Psalm 30:5 — Weeping may endure for a night, but joy cometh in the morning.",
"Psalm 51:10 — Create in me a clean heart, O God; and renew a right spirit within me.",
"Psalm 84:11 — For the LORD God is a sun and shield: the LORD will give grace and glory.",
"Psalm 103:2 — Bless the LORD, O my soul, and forget not all his benefits.",
"Psalm 121:1 — I will lift up mine eyes unto the hills, from whence cometh my help.",
"Psalm 121:2 — My help cometh from the LORD, which made heaven and earth.",
"Psalm 127:1 — Except the LORD build the house, they labour in vain that build it.",
"Proverbs 4:23 — Keep thy heart with all diligence; for out of it are the issues of life.",
"Proverbs 18:10 — The name of the LORD is a strong tower: the righteous runneth into it, and is safe.",
"Proverbs 22:6 — Train up a child in the way he should go: and when he is old, he will not depart from it.",
"Isaiah 54:17 — No weapon that is formed against thee shall prosper.",
"Jeremiah 1:8 — Be not afraid of their faces: for I am with thee to deliver thee, saith the LORD.",
"Jeremiah 33:3 — Call unto me, and I will answer thee, and shew thee great and mighty things.",
"Matthew 5:16 — Let your light so shine before men, that they may see your good works.",
"Matthew 7:7 — Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.",
"Matthew 28:20 — Lo, I am with you alway, even unto the end of the world.",
            "Mark 12:30 — And thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind.",
"Mark 12:31 — Thou shalt love thy neighbour as thyself.",
"Luke 11:28 — Blessed are they that hear the word of God, and keep it.",
"Luke 18:27 — The things which are impossible with men are possible with God.",
"John 10:10 — I am come that they might have life, and that they might have it more abundantly.",
"John 13:34 — A new commandment I give unto you, That ye love one another; as I have loved you.",
"John 16:33 — Be of good cheer; I have overcome the world.",
"Acts 20:35 — It is more blessed to give than to receive.",
"Romans 10:9 — That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved.",
"Romans 12:12 — Rejoicing in hope; patient in tribulation; continuing instant in prayer.",
"Romans 15:13 — Now the God of hope fill you with all joy and peace in believing.",
"1 Corinthians 16:14 — Let all your things be done with charity.",
"2 Corinthians 4:16 — Though our outward man perish, yet the inward man is renewed day by day.",
"2 Corinthians 9:7 — God loveth a cheerful giver.",
"Galatians 6:9 — And let us not be weary in well doing: for in due season we shall reap, if we faint not.",
"Ephesians 3:20 — Now unto him that is able to do exceeding abundantly above all that we ask or think.",
"Ephesians 4:32 — And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you.",
"Philippians 1:6 — He which hath begun a good work in you will perform it until the day of Jesus Christ.",
"Philippians 2:3 — In lowliness of mind let each esteem other better than themselves.",
"Philippians 4:8 — Think on these things.",
"Colossians 3:23 — And whatsoever ye do, do it heartily, as to the Lord, and not unto men.",
"1 Thessalonians 5:21 — Prove all things; hold fast that which is good.",
"2 Thessalonians 3:3 — But the Lord is faithful, who shall stablish you, and keep you from evil.",
"1 Timothy 4:12 — Let no man despise thy youth; but be thou an example of the believers.",
"2 Timothy 2:15 — Study to shew thyself approved unto God, a workman that needeth not to be ashamed.",
"Titus 3:5 — Not by works of righteousness which we have done, but according to his mercy he saved us.",
"Philemon 1:7 — For we have great joy and consolation in thy love.",
"Hebrews 4:16 — Let us therefore come boldly unto the throne of grace.",
"Hebrews 10:23 — Let us hold fast the profession of our faith without wavering; for he is faithful that promised.",
"Hebrews 12:2 — Looking unto Jesus the author and finisher of our faith.",
"James 1:22 — But be ye doers of the word, and not hearers only.",
"James 4:8 — Draw nigh to God, and he will draw nigh to you.",
"1 Peter 2:9 — But ye are a chosen generation, a royal priesthood, an holy nation, a peculiar people.",
"1 Peter 3:15 — But sanctify the Lord God in your hearts.",
"2 Peter 1:3 — According as his divine power hath given unto us all things that pertain unto life and godliness.",
"1 John 3:18 — My little children, let us not love in word, neither in tongue; but in deed and in truth.",
"1 John 5:14 — And this is the confidence that we have in him, that, if we ask any thing according to his will, he heareth us.",
"Jude 1:24 — Now unto him that is able to keep you from falling, and to present you faultless before the presence of his glory with exceeding joy.",
"Revelation 2:10 — Be thou faithful unto death, and I will give thee a crown of life.",
"Revelation 22:12 — And, behold, I come quickly; and my reward is with me.",
"Psalm 1:1 — Blessed is the man that walketh not in the counsel of the ungodly.",
"Psalm 18:2 — The LORD is my rock, and my fortress, and my deliverer.",
"Psalm 31:24 — Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD.",
"Psalm 40:1 — I waited patiently for the LORD; and he inclined unto me, and heard my cry.",
"Psalm 63:1 — O God, thou art my God; early will I seek thee.",
"Psalm 86:11 — Teach me thy way, O LORD; I will walk in thy truth.",
"Psalm 118:24 — This is the day which the LORD hath made; we will rejoice and be glad in it.",
"Psalm 119:11 — Thy word have I hid in mine heart, that I might not sin against thee.",
"Psalm 133:1 — Behold, how good and how pleasant it is for brethren to dwell together in unity!",
"Proverbs 12:25 — Heaviness in the heart of man maketh it stoop: but a good word maketh it glad.",
"Proverbs 15:1 — A soft answer turneth away wrath: but grievous words stir up anger.",
"Proverbs 17:17 — A friend loveth at all times, and a brother is born for adversity.",
"Proverbs 27:17 — Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.",
"Isaiah 12:2 — Behold, God is my salvation; I will trust, and not be afraid.",
"Isaiah 58:11 — And the LORD shall guide thee continually, and satisfy thy soul in drought.",
"Jeremiah 32:27 — Behold, I am the LORD, the God of all flesh: is there any thing too hard for me?",
"Matthew 5:9 — Blessed are the peacemakers: for they shall be called the children of God.",
"Matthew 6:21 — For where your treasure is, there will your heart be also.",
"Matthew 18:20 — For where two or three are gathered together in my name, there am I in the midst of them.",
"Luke 12:32 — Fear not, little flock; for it is your Father's good pleasure to give you the kingdom.",
"John 6:35 — I am the bread of life: he that cometh to me shall never hunger.",
"John 15:12 — This is my commandment, That ye love one another, as I have loved you.",
"Romans 8:31 — If God be for us, who can be against us?",
"Hebrews 13:8 — Jesus Christ the same yesterday, and to day, and for ever."

        };
    }
}
