package com.kingdomlife.app;

public class DailyChallengeData {

    public static String[] getChallenges() {
        return new String[] {
            "Read today's Bible verse and thank God for one thing it reminds you of.",
"Spend a few minutes praising God for who He is, not only for what He gives.",
"Thank God for three things you have today that you sometimes take for granted.",
"Read a short Bible passage and write down one lesson you can apply today.",
"Pray for someone who may be having a difficult day.",
"Encourage someone today with sincere and uplifting words.",
"Before making an important decision today, ask God for wisdom.",
"Do one helpful thing for someone without waiting to be asked.",
"Read a Psalm and identify one reason the writer gives for praising God.",
"Think of one time God helped you in the past and thank Him for His faithfulness.",
"Practice patience today when something does not go the way you expected.",
"Take a few quiet minutes to talk to God honestly about your day.",
"Choose honesty today, even when telling the truth may be uncomfortable.",
"Thank God for someone who has positively influenced your life.",
"Finish one useful task you have been putting off.",
"Read today's verse twice and think about how it can guide your actions.",
"Show kindness to someone who may not expect it from you.",
"Spend some time praising God through prayer, worship, or a song.",
"Ask God to help you become more like Christ in one area of your life.",
"At the end of today, name three things you are grateful to God for.",
            "Begin your day by thanking God for the gift of life.",
"Pray for your family and ask God to guide and protect them.",
"Find one Bible verse about gratitude and reflect on its message.",
"Praise God for something He has brought you through.",
"Help with a responsibility at home without being reminded.",
"Read a Bible passage about faith and identify one way you can trust God more.",
"Encourage someone who may need hope today.",
"Thank God for the people who support and care for you.",
"Choose gentle words today, especially when you disagree with someone.",
"Spend a few minutes praising God for His goodness and faithfulness.",
"Think of one mistake you made recently and ask God for wisdom to learn from it.",
"Pray for someone you know who needs strength or encouragement.",
"Read a Psalm and write down one phrase that encourages you.",
"Do something kind for someone without expecting anything in return.",
"Thank God for one difficult experience that taught you something valuable.",
"Practice self-control today by pausing before reacting when you are upset.",
"Ask God to help you use your abilities to help someone else.",
"Read about a Bible character who showed courage and identify one lesson from their example.",
"Take time today to praise God for His creation.",
"Before going to sleep, thank God for three moments from today that you appreciated.",
            "Read today's Bible verse and ask yourself how you can live it out.",
"Thank God for an answered prayer, whether recent or from the past.",
"Pray for someone who has encouraged you in your faith.",
"Choose to forgive someone instead of holding onto resentment.",
"Praise God today for His mercy and patience.",
"Read a short Bible passage and share one lesson from it with someone.",
"Do something helpful for your family today without being asked.",
"Thank God for a lesson you learned from a difficult season.",
"Spend a few quiet minutes listening, reflecting, and talking to God.",
"Encourage someone by reminding them of something good about them.",
"Read a Psalm and find one reason the writer praises God.",
"Ask God to help you make wise choices today.",
"Practice patience when someone makes a mistake or takes longer than expected.",
"Thank God for the abilities and opportunities He has given you.",
"Help someone learn something you know how to do.",
"Spend a few minutes praising God for His faithfulness.",
"Read about a Bible character who showed kindness and consider their example.",
"Pray for wisdom before responding to a difficult situation.",
"Write down three things you are grateful to God for today.",
"Complete one responsibility today with care and excellence.",
            "Thank God for a new day and ask Him to help you use it wisely.",
"Read a Bible passage about love and choose one way to show love today.",
"Praise God for a quality about Him that you admire.",
"Pray for someone who needs encouragement today.",
"Notice one blessing you might normally overlook and thank God for it.",
"Choose to speak words that build others up instead of tearing them down.",
"Read today's verse and share what it means to you with someone you trust.",
"Help someone with a task that is difficult for them.",
"Thank God for a person who has taught you something valuable.",
"Spend a few minutes praising God and remembering His faithfulness.",
"Ask God to help you respond wisely instead of reacting quickly today.",
"Read about a Bible character who faced difficulty and identify what you can learn.",
"Do one kind thing for someone who may be having a difficult day.",
"Pray for your school, community, church, or the people around you.",
"Thank God for something beautiful you notice in creation today.",
"Practice humility today by being willing to listen and learn from others.",
"Read a Psalm and find one verse or idea that gives you hope.",
"Complete something you started instead of leaving it unfinished.",
"Praise God for His guidance and ask Him to direct your choices today.",
"Before bed, reflect on the day and thank God for His presence through it.",
            "Begin today by praising God for His goodness and mercy.",
"Thank God for three people who have made a positive difference in your life.",
"Read a short Bible passage and identify one command you can practice.",
"Pray for someone who needs God's strength today.",
"Choose patience when you are tempted to become frustrated.",
"Thank God for a blessing you received that you did not expect.",
"Encourage someone by telling them something genuinely positive about them.",
"Read a Psalm and find one reason to trust God.",
"Ask God to help you use your words wisely today.",
"Do one helpful task at home without being reminded.",
"Praise God for His faithfulness, even when circumstances are difficult.",
"Think about one area where you need to grow and pray about it.",
"Read today's verse and spend a few minutes reflecting on its message.",
"Thank God for an opportunity to learn something new.",
"Pray for someone you normally do not think to pray for.",
"Show kindness to someone today without expecting recognition.",
"Read about a Bible character who demonstrated faith and learn from their example.",
"Take a quiet moment to thank God simply for being with you.",
"Choose honesty and integrity in everything you do today.",
"Before sleeping, remember one good thing from today and give God thanks.",
            "Thank God for the strength He gives you to face each new day.",
"Read a Bible passage about gratitude and reflect on its message.",
"Praise God for one way you have seen His goodness recently.",
"Pray for a friend and ask God to bless and guide them.",
"Choose to encourage someone instead of criticizing them today.",
"Thank God for a lesson you learned from a past experience.",
"Read today's verse and think of one action it inspires you to take.",
"Help someone who is struggling with a task.",
"Spend a few quiet minutes praising God for His love.",
"Ask God to give you wisdom before making an important choice.",
"Thank God for your family and pray for each member.",
"Practice kindness toward someone who may be difficult to understand.",
"Read a Psalm and find something about God's character to praise Him for.",
"Complete an important responsibility before spending time on entertainment.",
"Pray for someone facing a challenge that you know about.",
"Thank God for one ability or talent you can use to help others.",
"Choose peaceful words when you disagree with someone.",
"Praise God for His forgiveness and ask Him to help you forgive others.",
"Read about a Bible character who showed perseverance and learn from their example.",
"End your day by naming three things you can sincerely thank God for.",
            "Start today by thanking God for another opportunity to grow.",
"Read a short Bible passage and write down one thing that stood out to you.",
"Praise God for His wisdom and ask Him to guide your decisions.",
"Pray for someone who may feel discouraged today.",
"Thank God for a person who has shown you kindness.",
"Choose to be patient when someone frustrates you.",
"Do one act of kindness that makes someone else's day easier.",
"Read today's verse and think about how it applies to your life.",
"Ask God to help you become more dependable in your responsibilities.",
"Spend a few minutes praising God for His creation.",
"Thank God for something you once prayed for that He eventually provided.",
"Encourage someone who is working hard toward a goal.",
"Read about a Bible character who made a wise decision and learn from it.",
"Pray for wisdom before giving advice to someone.",
"Choose to listen carefully instead of interrupting today.",
"Thank God for the people who have helped you grow.",
"Do a responsibility today with a willing and cheerful attitude.",
"Praise God for His presence during both good and difficult times.",
"Read a Psalm and identify one sentence or idea that encourages you.",
"Before bed, thank God for one lesson you learned today."

        };
    }
}
